<?php
$row_projet = 
array(
    array(
        "id_projet" => "1",
        "activation_projet" => "",
        "id_general" => "",
        "type_projet" => "",
        "id_user_projet" => "",
        "id_sha1_user_projet" => "1745733679",
        "id_sha1_projet" => "1745992155",
        "id_sha1_projet_lock" => "",
        "id_sha1_projet_song" => "1",
        "color_projet" => "",
        "google_title_projet" => "114,105,101,110,95,97,95,118,111,105,114,101,101,101,101,101",
        "level_urgence_projet" => "",
        "change_meta_name_projet" => "",
        "change_meta_name_projet_toggle" => "",
        "change_meta_content_projet" => "",
        "change_meta_content_projet_toggle" => "",
        "id_sha1_parent_projet" => "",
        "id_sha1_parent_projet2" => "",
        "cryptage_projet" => "",
        "html_mode_projet_1" => "",
        "html_mode_projet_2" => "",
        "style_pages_projet" => "",
        "name_pages_projet" => "",
        "input_cryptage_projet" => "",
        "name_projet" => "",
        "name_extention_projet" => "",
        "statue_projet" => "",
        "title_projet" => "84,105,116,114,101,32,100,101,32,109,111,110,32,80,114,111,106,101,116",
        "title_projet_toggle" => "",
        "description_projet" => "",
        "description_projet_toggle" => "",
        "password_projet" => "",
        "visibility_1_projet" => "1",
        "visibility_2_projet" => "",
        "screen_shoot_projet" => "",
        "img_projet_src1" => "uploads/1745992155_1745992194.jpg",
        "img_projet_src1_toggle" => "",
        "total_style_pages" => "",
        "total_style_parent_pages" => "",
        "total_style_text_pages" => "",
        "img_projet_src2" => "",
        "img_projet_src2_toggle" => "",
        "img_projet_visibility" => "",
        "group_projet" => "",
        "heure_debut_projet" => "",
        "date_debut_projet" => "",
        "dure_projet" => "",
        "publication_date_j_projet" => "",
        "publication_date_h_projet" => "",
        "shop_projet" => "",
        "date_inscription_projet" => "2025-04-30 08:30:22",
    ),
);
?>